name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    env:
      PROGRAM: MicFix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Select Xcode 12
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12"
      
      - name: Build binary
        run: xcodebuild archive -scheme ${PROGRAM} -archivePath build

      - name: Set version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Package to zip
        id: zip
        run: |
          dir=${PROGRAM}-Release-${{ steps.version.outputs.tag }}
          echo ::set-output name=filename::${dir}
          mkdir ${dir}
          cp build.xcarchive/Products/${PROGRAM} ${dir}
          cp scripts/* ${dir}
          zip -r ${dir}.zip ${dir}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.zip.outputs.filename }}.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}